import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css';
import axios from 'axios';
import router from 'next/router';

export default function AddCongrats() {

    const [nome, setNome] = useState("");
    const [mensagem, setMensagem] = useState("");

    const saveMessage = () => {
        console.log(nome);
        console.log(mensagem);

        const data = {
            NOME: nome,
            DESCRICAO: mensagem
        }

        axios.post("https://webapimydelivery.com.br/_api/comemoracao/recado", data)
            .then(function (res) {
                router.push("/");
            })
            .catch(function (err) {
                alert(JSON.stringify(err));
            })
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>Digite seu nome</h1>
                <input type="text" placeholder="Digite seu nome" onBlur={(e) => { setNome(e.target.value) }} />
                <h1 className={styles.title}>Digite sua mensagem</h1>
                <textarea maxLength={200} onBlur={(e) => { setMensagem(e.target.value) }}></textarea>
                <div className={styles.btnSalvar} onClick={saveMessage}>Salvar</div>
            </main>
        </div>
    )
}